class CoffeeModel {
  final String name;
  final String imageAsset;
  final String image;
  final String description;
  final String description2;
  final String origin;
  final String brewingMethod;
  final String tasteProfile;
  final String caffeineLevel;
  final String funFact;
  bool isFavorite;

  CoffeeModel({
    required this.name,
    required this.imageAsset,
    required this.image,
    required this.description,
    required this.description2,
    required this.origin,
    required this.brewingMethod,
    required this.tasteProfile,
    required this.caffeineLevel,
    required this.funFact,
    this.isFavorite=false,
  });
}

List<CoffeeModel> coffees = [
  CoffeeModel(
    name: 'Cappuccino',
    imageAsset: 'assets/images/cappuccino.jpeg',
    image: 'assets/images/cappuccino_details.jpeg',
    description: 'Espresso with milk and foam.',
    description2: 'A perfect combination of espresso, steamed milk, and foam.',
    origin: 'Italy',
    brewingMethod: 'Espresso machine, steam milk',
    tasteProfile: 'Creamy, Sweet, Balanced',
    caffeineLevel: 'Medium',
    funFact: 'Cappuccino is named after the Capuchin friars due to the color of their robes.',
  ),
  CoffeeModel(
    name: 'Flat White',
    imageAsset: 'assets/images/flatwhite.jpg',
    image: 'assets/images/flat_white_details.jpeg',
    description: 'Espresso with smooth microfoam.',
    description2: 'A smooth, creamy coffee made with espresso and steamed milk.',
    origin: 'Australia or New Zealand',
    brewingMethod: 'Espresso with steamed milk and microfoam',
    tasteProfile: 'Creamy, Smooth, Subtle',
    caffeineLevel: 'Medium',
    funFact: 'The flat white is a subject of a long-standing debate between Australia and New Zealand regarding its origin.',
  ),
  CoffeeModel(
    name: 'Americano',
    imageAsset: 'assets/images/americano.jpg',
    image: 'assets/images/americano_details.jpeg',
    description: 'Espresso diluted with hot water.',
    description2: 'A simple coffee made by diluting espresso with hot water.',
    origin: 'Italy',
    brewingMethod: 'Espresso, hot water',
    tasteProfile: 'Smooth, Bitter, Strong',
    caffeineLevel: 'High',
    funFact: 'The Americano became popular during WWII when American soldiers in Italy diluted espresso with water to mimic their home-style coffee.',
  ),
  CoffeeModel(
    name: 'Latte',
    imageAsset: 'assets/images/latte.jpg',
    image: 'assets/images/latte_details.jpeg',
    description: 'Espresso with lots of steamed milk.',
    description2: 'A creamy espresso drink made with steamed milk and topped with a little foam.',
    origin: 'Italy',
    brewingMethod: 'Espresso, steamed milk, light foam',
    tasteProfile: 'Creamy, Mellow, Mild',
    caffeineLevel: 'Medium',
    funFact: 'The word "latte" comes from the Italian phrase "caffè latte," meaning "milk coffee."',
  ),
  CoffeeModel(
    name: 'Macchiato',
    imageAsset: 'assets/images/macchiato.jpg',
    image: 'assets/images/caffee_machiatto_details.jpeg',
    description: 'Espresso with a touch of foam.',
    description2: 'A strong espresso with just a touch of steamed milk.',
    origin: 'Italy',
    brewingMethod: 'Espresso, splash of milk',
    tasteProfile: 'Bold, Strong, Bitter',
    caffeineLevel: 'High',
    funFact: 'The word "macchiato" means "stained" or "spotted" in Italian, referring to the milk staining the espresso.',
  ),
  CoffeeModel(
    name: 'Mocha',
    imageAsset: 'assets/images/mocha.jpg',
    image: 'assets/images/mocha_details.jpeg',
    description: 'Espresso with milk and chocolate.',
    description2: 'A chocolatey, creamy coffee drink made with espresso, steamed milk, and whipped cream.',
    origin: 'Italy',
    brewingMethod: 'Espresso, chocolate syrup, steamed milk, whipped cream',
    tasteProfile: 'Sweet, Chocolatey, Creamy',
    caffeineLevel: 'Medium',
    funFact: 'The Mocha is named after the Yemeni port city of Mocha, a major coffee trade center during the 15th century.',
  ),
  CoffeeModel(
    name: 'Espresso',
    imageAsset: 'assets/images/espresso.jpg',
    image: 'assets/images/espresso_details.jpeg',
    description: 'Strong, concentrated coffee shot.',
    description2: 'A small, concentrated coffee made by forcing steam through ground coffee beans.',
    origin: 'Italy',
    brewingMethod: 'Espresso machine',
    tasteProfile: 'Bitter, Strong, Bold',
    caffeineLevel: 'Very High',
    funFact: 'Espresso is the base for many popular coffee drinks.',
  ),
  CoffeeModel(
    name: 'Cortado',
    imageAsset: 'assets/images/cortado.jpg',
    image: 'assets/images/cortado_details.jpg',
    description: 'Espresso with equal steamed milk.',
    description2: 'A balanced drink of espresso and steamed milk, providing a smooth texture.',
    origin: 'Spain',
    brewingMethod: 'Espresso, steamed milk',
    tasteProfile: 'Balanced, Strong, Smooth',
    caffeineLevel: 'High',
    funFact: 'Cortado means "cut" in Spanish, referring to how the milk "cuts" the espresso.',
  ),
  CoffeeModel(
    name: 'Affogato',
    imageAsset: 'assets/images/affogato.jpg',
    image: 'assets/images/affogato_details.jpg',
    description: 'Espresso over vanilla ice cream.',
    description2: 'A perfect treat combining espresso and ice cream.',
    origin: 'Italy',
    brewingMethod: 'Espresso shot',
    tasteProfile: 'Bitter, Sweet, Creamy',
    caffeineLevel: 'High',
    funFact: 'The word "affogato" means "drowned" in Italian.',
  ),
  CoffeeModel(
    name: 'Irish Coffee',
    imageAsset: 'assets/images/irish.jpeg',
    image: 'assets/images/irish_coffee_details.jpeg',
    description: 'Coffee mixed with Irish whiskey.',
    description2: 'A warming coffee cocktail made with hot coffee, Irish whiskey, and cream.',
    origin: 'Ireland',
    brewingMethod: 'Hot coffee, Irish whiskey, sugar, cream',
    tasteProfile: 'Rich, Warm, Whiskey-flavored',
    caffeineLevel: 'Medium',
    funFact: 'Irish coffee was invented at Shannon Airport in Ireland in the 1940s.',
  ),
  CoffeeModel(
    name: 'Iced Coffee',
    imageAsset: 'assets/images/icedcoffee.jpeg',
    image: 'assets/images/iced_coffee_details.jpg',
    description: 'Chilled coffee served over ice.',
    description2: 'Brewed coffee cooled down and served with ice, often with milk or sweetener.',
    origin: 'Global',
    brewingMethod: 'Brewed coffee, ice',
    tasteProfile: 'Smooth, Refreshing, Bold',
    caffeineLevel: 'Medium',
    funFact: 'Iced coffee became popular in the U.S. in the 20th century, especially in warmer climates.',
  ),
  CoffeeModel(
    name: 'Frappe',
    imageAsset: 'assets/images/frappe.jpg',
    image: 'assets/images/frappe_details.jpg',
    description: 'Blended iced coffee with foam.',
    description2: 'A refreshing, creamy iced coffee drink.',
    origin: 'Greece',
    brewingMethod: 'Instant coffee blend',
    tasteProfile: 'Sweet, Icy, Refreshing',
    caffeineLevel: 'Medium',
    funFact: 'Frappes became popular during the 1957 Thessaloniki Expo.',
  ),
  CoffeeModel(
    name: 'Turkish Coffee',
    imageAsset: 'assets/images/turkishcoffee.jpg',
    image: 'assets/images/turkish_coffee_details.jpg',
    description: 'Strong, thick unfiltered coffee.',
    description2: 'A rich, thick coffee brewed in a special pot called a cezve.',
    origin: 'Turkey, Middle East, Balkans',
    brewingMethod: 'Finely ground coffee, water, sugar, cezve',
    tasteProfile: 'Rich, Thick, Strong',
    caffeineLevel: 'High',
    funFact: 'Turkish coffee is often served with Turkish delight.',
  ),
  CoffeeModel(
    name: 'Drip Coffee',
    imageAsset: 'assets/images/dripcoffee.jpg',
    image: 'assets/images/drip_coffee_details.jpg',
    description: 'Brewed by dripping hot water.',
    description2: 'A simple brewing method where water is poured over coffee grounds.',
    origin: 'Global',
    brewingMethod: 'Drip coffee maker, or pour-over',
    tasteProfile: 'Smooth, Balanced, Mild',
    caffeineLevel: 'Medium',
    funFact: 'Drip coffee is the most common method in the U.S.',
  ),
  CoffeeModel(
    name: 'Lungo',
    imageAsset: 'assets/images/lungo.jpg',
    image: 'assets/images/lungo_details.jpeg',
    description: 'Longer espresso with more water',
    description2: 'A longer version of espresso made with more water, resulting in a larger, milder cup.',
    origin: 'Italy',
    brewingMethod: 'Espresso machine with more water',
    tasteProfile: 'Smooth, Bitter, Rich',
    caffeineLevel: 'High',
    funFact: 'The word "lungo" means "long" in Italian, referring to the longer brewing time and more water.',
  ),
  CoffeeModel(
    name: 'Red Eye',
    imageAsset: 'assets/images/Red-Eye.jpg',
    image: 'assets/images/red_eye_details.jpg',
    description: 'Drip coffee with an espresso shot.',
    description2: 'A strong, caffeine-packed drink made by adding a shot of espresso to a regular brewed coffee.',
    origin: 'United States',
    brewingMethod: 'Brewed coffee with a shot of espresso',
    tasteProfile: 'Bold, Strong, Rich',
    caffeineLevel: 'Very High',
    funFact: 'The Red Eye is sometimes referred to as a "shot in the dark" because of the added espresso shot.',
  ),
];
